// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/SamedArslan28/gopost/internal/database"
	"github.com/SamedArslan28/gopost/internal/handler"
	"github.com/SamedArslan28/gopost/internal/repository"
	"github.com/SamedArslan28/gopost/internal/service"
)

// Injectors from wire.go:

func InitializeApp(dbDsn string) (*Server, error) {
	db, err := database.ConnectDB(dbDsn)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userHandler := provideUserHandler(userService)
	server := NewServer(userHandler)
	return server, nil
}

// wire.go:

// provideUserHandler is a helper provider.
// Your original code was: handler.NewUserHandler(*userService)
// This function replicates that logic so Wire can use it.
func provideUserHandler(userService *service.UserService) handler.UserHandler {

	userHandlerPointer := handler.NewUserHandler(*userService)

	return *userHandlerPointer
}
